### ISSUE TITLE
Flushing interval not configurable

### ISSUE THREAD

**Issue by jtmalinowski** [signalfx/splunk-otel-js#198]
While migrating from `signalfx-nodejs-tracing` (npm: `signalfx-tracing`) users might be unable to set the flushing interval to a desired value, if they needed to customize that setting previously.

**Comment by seemk** [comment]
It's configurable via `OTEL_BSP_SCHEDULE_DELAY`, however the BSP itself does not work properly at the moment (https://github.com/open-telemetry/opentelemetry-js/issues/3094)
