### ISSUE TITLE
Specifying custom propagator during initialization

### ISSUE THREAD

**Issue by maxmil7** [signalfx/splunk-otel-js#22]
For our usecase, we would like to override the default B3Propagator with our custom propagator implementation (slightly modified version of the B3 propagator). 
Initially, I thought of using `api.propagation.setGlobalPropagator` after calling `startTracing` but it seems to work differently than what I thought.
Would be great if you can add support for this. Thanks.

**Comment by maxmil7** [comment]
@owais it looks like this was being discussed [here](https://github.com/signalfx/splunk-otel-js/pull/3/files#r583610816). Just ran into this issue..

**Comment by maxmil7** [comment]
Debugged a bit further, I was pulling in the `1.0.0-rc.0` of `@opentelemetry/api` module, whereas SFx distribution pulls in `^0.18.0` Hence, when I tried to override the propagator, it was stored under [v1 major version](https://github.com/open-telemetry/opentelemetry-js-api/blob/main/src/internal/global-utils.ts#L27-L28) key where as SFx propagator was stored under `v0` major version.

Once, I updated my module to use `^0.18` of `@opentelemetry/api`, the system tried to override the propagator but because the `allowOverride` flag wasn't set when the propagator was [initially](https://github.com/signalfx/splunk-otel-js/blob/main/src/tracing.ts#L34-L36) set, it defaulted to `false` and threw  an error during override.

So unfortunately, I don't think there is a way to override w/o adding the feature in this module

**Comment by owais** [comment]
Thanks for opening this @maxmil7. This is a planned feature. I'll try to prioritize it and see if we can have this in next release (hopefully by end of this week).

**Comment by owais** [comment]
@maxmil7 released 0.5.0 that should allow you to configure a custom propagator.

**Comment by maxmil7** [comment]
Thank you! I should be able to test it out by tomorrow. Will let you know if I run into any issues. Closing the issue for now.
