### ISSUE TITLE
Unhandled promise rejection: 'Failed to send datapoint' on ECONNREFUSED

### ISSUE THREAD

**Issue by andrew-prior** [signalfx/splunk-otel-js#428]
The metrics reporting throws this error `error: Failed to send datapoint:  undefined Error: connect ECONNREFUSED 127.0.0.1:9080
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9080
}` if it cannot send the metrics. Unfortunately, there is no way to catch the error in my application. The [metrics are sent using the signalFx client](https://github.com/signalfx/splunk-otel-js/blob/a21db72b8d801e6f87642466102f343912bd2750/src/metrics/index.ts#L249) from within [a `setInterval` function](https://github.com/signalfx/splunk-otel-js/blob/a21db72b8d801e6f87642466102f343912bd2750/src/metrics/index.ts#L102), neither the splunk-otel-js library or the signalfx-nodejs library implement error handling for this promise rejection. 

I have raised an issue on the [signalfx-nodejs library](https://github.com/signalfx/signalfx-nodejs/issues/70) as well.

**Comment by andrew-prior** [comment]
We only use otel. This error results from splunk-otel-js using the singalFx client internally.

**Comment by seemk** [comment]
Agree, my question was that we're switching internally from SignalFx to OTel metrics SDK in a week or two - basically as soon as the new OTel SDK lands in NPM.

For you it would only matter if you're currently using custom metrics via the SignalFx agent, runtime metrics will be converted to OTel metrics transparently.

**Comment by seemk** [comment]
Closing this because as of 2.0.0 we have removed SignalFx from the repository
