### ISSUE TITLE
Defaults not set for exporter when using options.defaultSpanExporterFactory(options)

### ISSUE THREAD

**Issue by maxmil7** [signalfx/splunk-otel-js#47]
Hi Splunk team,

In my application I am getting a handle on the `defaultSpanExporter` using `options.defaultSpanExporterFactory(options)` API and then using the exporter as one of the exporters in a custom `spanProcessorFactory` function

```
const { defaultSpanExporterFactory } = require('@splunk/otel/lib/options');
const exporterInstance = new defaultSpanExporterFactory(options);
```
I ran into an issue where I wasn't specifying the endpoint in the options and as a result the endpoint was set as undefined. 

I am wondering whether it would be better to set the default options for the exporter within the [defaultSpanExporterFactory](https://github.com/signalfx/splunk-otel-js/blob/main/src/options.ts#L107) itself instead of the [_setDefaultOptions](https://github.com/signalfx/splunk-otel-js/blob/main/src/options.ts#L57) function so exporter specific options would be normalized even if `defaultSpanExporterFactory` is directly used?

Or do you recommend supplying all options if we directly try to use the `defaultSpanExporterFactory`?

**Comment by owais** [comment]
> Or do you recommend supplying all options if we directly try to use the defaultSpanExporterFactory?

Short answer: yes.

Long answer:

The idea was that we'd process options, load it with default for missing values, parse/validate any fields that require it and pass on the "processed" options to the factories so factories could rely on options always being correct. As a result, the default factories will always rely on fields being set in `options` object they receive. 

Custom factories are free to either use options or completely ignore it and use custom or even hard-coded values.

**Comment by maxmil7** [comment]
Thanks. Closing it for now. Will re-open if I come across something similar.
