### ISSUE TITLE
Custom splunk logger

### ISSUE THREAD

**Issue by maxmil7** [signalfx/splunk-otel-js#49]
Hi @owais/team,

I am wondering if there is a plan to configure a logger in this distribution which will log to splunk backend. 
Or maybe a standalone splunk logger which can be initialized with opentelemetry context.
It would be great if there is an analogous logger which can be used with this distribution so that debug logs can flow into splunk backend and get stitched with the traces.
Would like to know your thoughts on this. Thanks.

**Comment by owais** [comment]
Logging is definitely on the roadmap but has not been fleshed out in OpenTelemetry yet so we most likely cannot ship a logger or a log exporter pipeline in this distro but we can definitely provide integration with popular loggers to automatically inject trace context into them. You can then configure your node apps to send logs to Splunk the way you do generally for all application. Would that be useful?

**Comment by maxmil7** [comment]
So if I understand correctly, there are some libraries which can be used to log to splunk such as [splunk-javascript-logging](https://github.com/splunk/splunk-javascript-logging) and the [splunk-bunyan-logger](https://github.com/splunk/splunk-bunyan-logger) extension for bunyan logger. 

What you are suggesting is providing a feature to inject trace context into the above libraries (or other popular logging libraries) so when they log to splunk backend, the trace context will get logged as well?

I think this can work. Only downside I see is once logging support is available in the Otel distribution, then apps will have to migrate to the new logging API. We can try to see if we can absorb some of the impact by writing a logging abstraction so the migration becomes easier later on.

Also, I apologize if I got this completely wrong. We use an in-house logging system currently so still need to explore what would be the best way for apps to start logging to splunk.

Assuming that trace context can be injected in the logs, will splunk/signalFx be able to automatically stitch together the logs and traces?

**Comment by owais** [comment]
> What you are suggesting is providing a feature to inject trace context into the above libraries (or other popular logging libraries) so when they log to splunk backend, the trace context will get logged as well?

Yes. It'd work with any library, not specific to Splunk's logging library at all. We'd actually just port the same feature from signalfx-nodejs-tracing to the new splunk-otel-js (https://github.com/signalfx/signalfx-nodejs-tracing/#inject-trace-information-with-bunyan-pino-or-winston)

**Comment by owais** [comment]
> I think this can work. Only downside I see is once logging support is available in the Otel distribution, then apps will have to migrate to the new logging API. We can try to see if we can absorb some of the impact by writing a logging abstraction so the migration becomes easier later on.

Makes sense but logging in Otel are still very nascent and it's very hard to tell what it'll look like. If we try to target it now, we'll end up creating a lot of breaking in splunk-otel-js as logging in Otel matures over the next few months. This'll cause a lot more pain as opposed to doing a one time migration.

**Comment by owais** [comment]
> Assuming that trace context can be injected in the logs, will splunk/signalFx be able to automatically stitch together the logs and traces?

I think it should be but might depend on the exact product you're using :) I'd suggest talking to a support engineer about it. You'll probably get a much more accurate and detailed answer from there.

**Comment by maxmil7** [comment]
Thank you for the details! I'll discuss this w/ our team and raise a feature request for the trace context integration.

**Comment by owais** [comment]
Closing this as the discussion has or should move on to a Splunk support channel.
