### ISSUE TITLE
Jaeger traces don't seem to be getting suppressed w/ v0.5.0

### ISSUE THREAD

**Issue by maxmil7** [signalfx/splunk-otel-js#50]
I upgraded to v0.5.0 and it seems that the Jaeger traces aren't getting suppressed anymore. As a result, application is continuously creating spans even if there are no incoming requests.

Added an example here (simple express app w/ out of box config) : https://github.com/maxmil7/async-demo/tree/sfx-distro (branch sfx-distro)

Upon hitting the index page we can see the following logs in console:
```
Creating span for request undefined
Creating span for request /
Creating span for request /v1/trace
Creating span for request /v1/trace
Creating span for request /v1/trace
Creating span for request /v1/trace
```

**Comment by owais** [comment]
Thanks. I'll look into this Tuesday (traveling tomorrow).

**Comment by owais** [comment]
Just ran a quick test but couldn't reproduce it. I see the log statement you mentioned above but I don't see any spans being generated for the Jaeger exporter. Neither do I see multiple, continuous log statements. When you run it, do you see "creating span for request /v1/trace" being printed infinitely after issuing a single request to http://localhost:7000/test ?

Which node version are you using?

**Comment by maxmil7** [comment]
I was using v10 earlier but tried w/ 12 and 14 as well. Able to reproduce in both versions 🤔 
Yes, I see the `creating span` statement infinitely every few seconds (guessing BatchSpanExporter might be buffering them). Attaching a screen recording of what I am seeing on my side

https://user-images.githubusercontent.com/3921810/112863237-7f811b00-906b-11eb-8d7d-d3df85b7dc91.mov

**Comment by owais** [comment]
Definitely looks like the exporter being traced but not sure how to repro yet. Will try again with same version of node.

**Comment by owais** [comment]
I can reproduce it with 14.7.0 but not with 15.x. This is a good. I'll dig deeper and let you know once I more info.

**Comment by owais** [comment]
@maxmil7 Thanks for the detailed example and screencast. Can you please try 0.6.0 and see if that fixes the issue?

**Comment by maxmil7** [comment]
Yes, v0.6.0 seems to work well. Thanks for the quick fix!
