### ISSUE TITLE
Support Node 18+

### ISSUE THREAD

**Issue by NavinSeth** [signalfx/splunk-otel-js#504]
In a Node 18.0.0 environment I can't install and use this as I get the following error. Is it possible to update the peer dependency SignalFx to 7.5.1 or is there a workaround?

<img width="476" alt="image" src="https://user-images.githubusercontent.com/36681806/178059924-ee0b6475-42a7-4e68-aaeb-87df1845032e.png">

**Comment by seemk** [comment]
This has been fixed in `@splunk/otel` `1.4.1`. Note we are moving to OTel metrics and getting rid of SignalFx libraries, but this will be a 2.0 release.
