### ISSUE TITLE
npm install @splunk/otel failing

### ISSUE THREAD

**Issue by rohits-splunk** [signalfx/splunk-otel-js#594]
Trying to run npm install @splunk/otel but is failing with below errors:

40351 warn enoent ENOENT: no such file or directory, open '/root/package.json'
40352 verbose enoent ENOENT: no such file or directory, open '/root/package.json'
40352 verbose enoent This is most likely not a problem with npm itself
40352 verbose enoent and is related to npm not being able to find a file.
40353 warn root No description
40354 verbose If you need help, you may report this error at:
40354 verbose     <https://github.com/npm/npm/issues>
40355 warn root No repository field.
40356 verbose If you need help, you may report this error at:
40356 verbose     <https://github.com/npm/npm/issues>
40357 warn root No README data
40358 verbose If you need help, you may report this error at:
40358 verbose     <https://github.com/npm/npm/issues>
40359 warn root No license field.
40360 verbose If you need help, you may report this error at:
40360 verbose     <https://github.com/npm/npm/issues>
40361 verbose stack Error: ENOTDIR: not a directory, open '/root/node_modules/.staging/@types/http-errors-5dc7903c/package.json'
40361 verbose stack     at Error (native)
40362 verbose cwd /root
40363 error Linux 5.15.49-linuxkit
40364 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@splunk/otel" "--save"
40365 error node v6.17.1
40366 error npm  v3.10.10
40367 error path /root/node_modules/.staging/@types/http-errors-5dc7903c/package.json
40368 error code ENOTDIR
40369 error errno -20
40370 error syscall open
40371 error ENOTDIR: not a directory, open '/root/node_modules/.staging/@types/http-errors-5dc7903c/package.json'
40372 error If you need help, you may report this error at:
40372 error     <https://github.com/npm/npm/issues>
40373 verbose exit [ -20, true ]

**Comment by seemk** [comment]
Is it when building a docker image?

**Comment by rohits-splunk** [comment]
Yes I need this image to deploy my app on the k8s cluster.

**Comment by seemk** [comment]
Which version is this related to?

From your logs I can see that Node version is `6.17.1`. As of 2.0.0 the minimum version is Node 14. The last 1.x version (1.4.1) has a minimum version of `12.13`.

Feel free to reopen if this isn't the case here.
