### ISSUE TITLE
Nexus IQ reporting Policy violation for protobufjs 6.11.2  

### ISSUE THREAD

**Issue by kumachop2** [signalfx/splunk-otel-js#597]
During build process Nexus IQ reporting Security-High Build warning with v1.14.1 as well as v2.0.0.0-rc2. My understanding protobufjs before 6.11.3 are vulnerable to Prototype Pollution which can allow an attacker to add/modify properties of the Object.prototype. Support team has communicated that v2.0 will be using 6.11.3, but I did noticed one module still referring to compromised version (6.9.0). Here is details and screens for reference.

    "node_modules/@opentelemetry/exporter-metrics-otlp-proto/node_modules/@grpc/proto-loader": {
      "version": "0.6.9",
      "resolved": "https://registry.npmjs.org/@grpc/proto-loader/-/proto-loader-0.6.9.tgz",
      "integrity": "sha512-UlcCS8VbsU9d3XTXGiEVFonN7hXk+oMXZtoHHG2oSA1/GcDP1q6OUgs20PzHDGizzyi8ufGSUDlk3O2NyY7leg==",
      "dependencies": {
        "@types/long": "^4.0.1",
        "lodash.camelcase": "^4.3.0",
        "long": "^4.0.0",
        "protobufjs": "^6.10.0",
        "yargs": "^16.2.0"
      },

![image](https://user-images.githubusercontent.com/107289628/199539762-8d2f46b5-7da0-466f-b342-5b5b95e606a4.png)

![image](https://user-images.githubusercontent.com/107289628/199540000-2be0e743-9d83-4ad5-af78-3c1cd6e07aa3.png)

Please let me know for additional information and remediating  timelines if any.  Much appreciated your help.

**Comment by seemk** [comment]
Deps have now been updated, will go into the next release (`2.0.0`)
