### ISSUE TITLE
Docs: explain how diag log level and OTEL_LOG_LEVEL env variable interact

### ISSUE THREAD

**Issue by sfishel-splunk** [signalfx/splunk-otel-js#598]
reading this docs section: https://github.com/signalfx/splunk-otel-js/blob/main/docs/troubleshooting.md

there is a log level being passed as the second argument to `diag.setLogger`, and there is mention of the `OTEL_LOG_LEVEL` environment variable. it's not clear if/how those two things interact

**Comment by seemk** [comment]
There's a new `logLevel` option now, when set it will set up the diagnostic logger with the given log level.

`OTEL_LOG_LEVEL` will now do the same (with the programmatic way having preference). See https://github.com/signalfx/splunk-otel-js/blob/main/docs/troubleshooting.md
