### ISSUE TITLE
Environment variables override explicit configuration

### ISSUE THREAD

**Issue by atoulme** [signalfx/splunk-otel-js#640]
I've been playing with the Node.js SDK a bit. The [doc](https://docs.splunk.com/Observability/gdi/get-data-in/application/nodejs/configuration/advanced-nodejs-otel-configuration.html) states Function arguments take precedence over the corresponding environment variables.
However, the code [here](https://github.com/signalfx/splunk-otel-js/blob/67e172a662f9399f20eb0f7e4cc43129a16811df/src/tracing/options.ts#L269-L275) explicitly disregards the endpoint we set if `SPLUNK_REALM` is set, with a warning:
```
      diag.warn(
        'OTLP span exporter factory: explicit endpoint ignored due to realm being set.'
      );
```

The realm env var is wrongfully taking precedence in this case even though the priority should always be programmatic way, then env vars.
It looks like it should be the other way round then - if explicit endpoint is set, the realm is ignored and a warning is given that the realm would be ignored.

**Comment by seemk** [comment]
Fixed in https://github.com/signalfx/splunk-otel-js/pull/668
