### ISSUE TITLE
Nexus IQ scanning alerted high vulnerability mysql 2.18.1 for latest version v2.2.0

### ISSUE THREAD

**Issue by kumachop2** [signalfx/splunk-otel-js#709]
Currently we are using Splunk Otel JS Agent v2.1.0 for Node JS app. 
Having  plan to upgrade agent version to 2.2.0 to address @sideway/formula but Nexus IQ scanning alerted high vulnerability on mysql 2.18.1 and affected version is [2.0.0-alpha,2.18.1]. 
Please do advice the availability of patched version of latest node js agent.
Appreciate your timely help.

![image](https://user-images.githubusercontent.com/107289628/228343450-ae9f545a-136a-4595-9a58-43b119dddb4c.png)

**Comment by kumachop2** [comment]
@seemk I do observed its reported in latest release v2.2.1 as well. Please advice

**Comment by seemk** [comment]
The recent versions should no longer have `mysql` in any of the dependencies

**Comment by seemk** [comment]
This should be resolved in newer versions, please reopen if the issue persists
