### ISSUE TITLE
Telemetry metrics as part of instrumentation plugins are not working

### ISSUE THREAD

**Issue by mkramb** [signalfx/splunk-otel-js#751]
A lot of the (standard) instrumentation plugins also emit metrics, \
for example [opentelemetry-instrumentation-http](https://github.com/open-telemetry/opentelemetry-js/blob/a675ae817b51ea6b8853e62ea460e3e944cd0930/experimental/packages/opentelemetry-instrumentation-http/src/http.ts#L79) or any custom plugins.

When following standard integration steps:
```
start({
   serviceName: '<service-name>',
  ...options
});
```

This will result in `meter` object being undefined, as `metrics.setGlobalMeterProvider` https://github.com/signalfx/splunk-otel-js/blob/cd86c089823b6df493eded9cda4c66678e0d09df/src/metrics/index.ts#L265 is called too late, as result no metrics in instrumentation plugins are emitted. 

For a workaround I have fallback to using `startMetric` first and then `startTracing`, as result metric are now emitted successfully, but unfortunately those methods are now marked as deprecated.

Is there a better way of doing this, or should individual start methods remain for this use-case.

**Comment by seemk** [comment]
Hi, which version of `@opentelemetry/api` are you using?

**Comment by seemk** [comment]
This should be resolved in `2.4.0` now. The instrumentation specific metrics are switched off by default, but can be enabled by setting `SPLUNK_INSTRUMENTATION_METRICS_ENABLED=true`.
