### ISSUE TITLE
Latest Otel JS Release

### ISSUE THREAD

**Issue by kumachop2** [signalfx/splunk-otel-js#768]
I'm looking for latest Otel JS version that should be bundle with Pull Request #753 changes. Please do advice.

**Comment by seemk** [comment]
Hi, 2.3.0 has been released now

**Comment by kumachop2** [comment]
@seemk Looks like package referencing to old version. Here is screens. Please check and advice.

v2.2.4:
![image](https://github.com/signalfx/splunk-otel-js/assets/107289628/8220bf1d-117f-4e12-84d9-5002515a55a0)

======================================================
v2.3.0:

![image](https://github.com/signalfx/splunk-otel-js/assets/107289628/5a72c4af-9464-42fb-b4e8-db96ca0bb697)

**Comment by kumachop2** [comment]
@seemk upon further analysis the latest version 2.3.0,  I assume below modules protobufjs still referring to before 7.2.4 versions

![image](https://github.com/signalfx/splunk-otel-js/assets/107289628/f20d00f3-e915-4e2c-afe4-c99adc0f40c3)

**Comment by kumachop2** [comment]
Please do open the caseThanks & Regards,Kumar.On Aug 2, 2023, at 3:37 PM, Siim Kallas ***@***.***> wrote:﻿
Closed #768 as completed.

**Comment by seemk** [comment]
Can you elaborate what's the current issue?

**Comment by kumachop2** [comment]
The latest OTEL JS 2.3.0 had updated protobuf version 7.2.4. But post performing NexusIQ scan I do noticed few modules still referring to previous protobuf version 7.2.3 instead of 7.2.4. Please do review the provided screens for modules that complained. On Aug 3, 2023, at 11:53 AM, Siim Kallas ***@***.***> wrote:﻿
Can you elaborate what's the current issue?

**Comment by seemk** [comment]
Can you show the security issue? From the screens it looks everything is using 7.2.4

**Comment by kumachop2** [comment]
@seemk Please find below screens that referring old versions in package-lock.json

![image](https://github.com/signalfx/splunk-otel-js/assets/107289628/423fe104-7848-4482-9172-529cb2224f8a)

![image](https://github.com/signalfx/splunk-otel-js/assets/107289628/8536234d-6785-4242-84c1-8f7dfff9947a)

![image](https://github.com/signalfx/splunk-otel-js/assets/107289628/6745b0f9-0949-4e68-964a-2fba76b69f8d)

**Comment by kumachop2** [comment]
@seemk I did performed NexusIQ scanning against Otel JS v2.4.0 but no luck, still policy violation reported for protobufjs : 7.2.4

**Comment by seemk** [comment]
Is this the same CVE as in this issue? https://github.com/protobufjs/protobuf.js/issues/1918

**Comment by kumachop2** [comment]
@seemk Please do provide update for bumping protobuf ( source & dist files) to 7.2.5 to address CVE. Appreciate your response.

**Comment by seemk** [comment]
@kumachop2 Version `2.6.1` of `@splunk/otel` now has protobuf.js `7.2.5`

**Comment by kumachop2** [comment]
@seemk Thank You for the upgrade and noticed still package-lock.json have protobuf.js 7.2.4 & 7.2.3 references. https://github.com/signalfx/splunk-otel-js/blob/198334632dcfe24a3adf8a6119df32285959d773/package-lock.json#L2419
