### ISSUE TITLE
Resource Detectors prorogate bugs that have long been fixed by opentelemtry-js

### ISSUE THREAD

**Issue by davemyers-dev** [signalfx/splunk-otel-js#923]
The resource detectors that were copied into this library, seemingly to work around an sync issue which was also fixed a year ago, continue to propagate issues that open telemetry has already fixed in their source. 

All of Otel's source detectors have been updated since they were copied.

Ex of a bug only present in this wrapper as a result:
https://github.com/open-telemetry/opentelemetry-js/issues/3295

Otel also made changes to allow synchronous detectors in https://github.com/open-telemetry/opentelemetry-js/issues/2912. This may mean that these do not need to be copied into this library at all.

Proposals:
Copied detectors should be removed from this library
or
Copied code should be properly maintained and updated with latest from source

**Comment by seemk** [comment]
With https://github.com/signalfx/splunk-otel-js/pull/925 detectors have been switched to upstream ones (with the exception of container detector).

However do note that spaces in resource attribute values need to be encoded as `%20`, see https://github.com/open-telemetry/opentelemetry-js/issues/3131

E.g.
`export OTEL_RESOURCE_ATTRIBUTES='service.name="foo bar"'`
needs to be written as 
`export OTEL_RESOURCE_ATTRIBUTES='service.name="foo%20bar"'`
