### ISSUE TITLE
Missing container image for 2.14.0 release 

### ISSUE THREAD

**Issue by OcamsRazor** [signalfx/splunk-otel-js#970]
Hi, I've noticed the latest available image is for `v2.13.0` but there is none for `v2.14.0`. The release commit on `2.x` has also not been merged into `main`.

**Comment by seemk** [comment]
It's now published, looks like there was a random failure when publishing

All upcoming version 2 releases are now done from the `2.x` branch, the current `main` branch is going to be used for a `3.0` release.
