### ISSUE TITLE
Error: PeriodicExportingMetricReader: metrics export failed

### ISSUE THREAD

**Issue by CatsMiaow** [signalfx/splunk-otel-js#976]
- @splunk/otel v2.14.0
- Node.js v20.18.0

```ts
import { start } from '@splunk/otel';

start({
  serviceName: process.env.xxx,
  endpoint: process.env.xxx,
  metrics: {
    endpoint: process.env.xxx,
    runtimeMetricsEnabled: true,
  },
  profiling: {
    memoryProfilingEnabled: true,
  },
  tracing: true,
});
```

```sh
/app/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:76
                throw new Error(`PeriodicExportingMetricReader: metrics export failed (error ${result.error})`);
                      ^
Error: PeriodicExportingMetricReader: metrics export failed (error Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error)
    at doExport (/app/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:76:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

When you start the application, an error occurs and the app crashes.

`@splunk/otel` v2.14.0 is using `@opentelemetry/sdk-metrics` v1.26.0
https://github.com/signalfx/splunk-otel-js/blob/c89f1a96e372347bc8e61eea49d6e91f4bb05941/package.json#L153

The bug with `PeriodicExportingMetricReader` seems to be fixed in [v1.27.0](https://github.com/open-telemetry/opentelemetry-js/releases/tag/v1.27.0), [v1.28.0](https://github.com/open-telemetry/opentelemetry-js/releases/tag/v1.28.0).

**Comment by seemk** [comment]
Thanks, I've released `2.15.0` which is using `sdk-metrics` `1.28.0`. Hopefully it resolves the issue, please reopen if you still see it.
